#!/usr/bin/env bash
# install-claude-launcher.sh
#
# Installs a thin wrapper at $KZ_ENG_MP_ROOT/agent-otel/bin/claude that
# augments OTEL_RESOURCE_ATTRIBUTES with host.name + project.name/path/repo
# before exec'ing the real Claude Code binary. The wrapper has to run
# *before* claude starts because the OTel SDK reads resource attributes
# at initialization — a SessionStart hook is too late.
#
# Install location follows the kamiwaza-engineering-marketplace tree so
# team tooling is co-located:
#   $KZ_ENG_MP_ROOT/agent-otel/bin/claude       (the wrapper)
# Falls back to ~/.kz-eng-mp/agent-otel/bin/claude if the env var isn't set.
#
# What this installer does:
#   1. Locate the current `claude` binary via PATH (must not already be
#      our wrapper).
#   2. Create the install dir if it doesn't exist.
#   3. Generate the wrapper with the absolute path to the real binary
#      baked in (so PATH ordering doesn't matter and we can't recurse
#      into ourselves).
#   4. Add the install dir to PATH at the front of the user's bash or
#      zsh rc, idempotently (marker-line guarded).
#
# Re-run any time to refresh — the wrapper will be regenerated with the
# currently-resolved real binary.
#
# Uninstall: delete the wrapper file and remove the marked block from
# ~/.zshrc or ~/.bashrc.

set -euo pipefail

# Allow the marketplace to override the root location via the standard
# env var; default matches the existing kz-eng-mp convention.
KZ_ENG_MP_ROOT="${KZ_ENG_MP_ROOT:-$HOME/.kz-eng-mp}"
INSTALL_DIR="${KZ_ENG_MP_ROOT}/agent-otel/bin"
WRAPPER_PATH="${INSTALL_DIR}/claude"
MARKER="# agent-otel: claude launcher"

# ---- 1. find the real claude --------------------------------------------

real_claude=$(command -v claude 2>/dev/null || true)
if [[ -z $real_claude ]]; then
  echo "ERROR: 'claude' not found in PATH. Install Claude Code first." >&2
  exit 1
fi

# Resolve symlinks so the wrapper points at the actual binary, not at
# itself if claude was symlinked into a directory we're about to put
# ourselves in.
real_resolved=$(readlink -f "$real_claude" 2>/dev/null || python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$real_claude")

if [[ $real_resolved == "$WRAPPER_PATH" ]]; then
  echo "ERROR: $real_claude resolves to the wrapper at $WRAPPER_PATH." >&2
  echo "       Either uninstall the wrapper first, or set REAL_CLAUDE explicitly:" >&2
  echo "         REAL_CLAUDE=/usr/local/bin/claude $0" >&2
  exit 1
fi

# Allow override (handy when the auto-detect picks a wrapper from a sibling tool)
real_claude=${REAL_CLAUDE:-$real_resolved}

# ---- 2. install dir ------------------------------------------------------

mkdir -p "$INSTALL_DIR"

# ---- 3. write the wrapper -----------------------------------------------

cat >"$WRAPPER_PATH" <<EOF
#!/usr/bin/env bash
# Auto-generated by agent-otel/tools/install-claude-launcher.sh
# Re-run the installer to update.
#
# Wraps the real Claude Code binary so each session emits OTel
# resource attributes for host + project — visible in AppMetrics
# / AppTraces Properties for multi-user analytics.

set -euo pipefail

REAL_CLAUDE="$real_claude"

# host: short hostname; falls back to full hostname if -s isn't supported.
host=\$(hostname -s 2>/dev/null || hostname)

# project: prefer git repo root; fall back to \$PWD basename.
if path=\$(git rev-parse --show-toplevel 2>/dev/null); then
  project=\$(basename "\$path")
  repo=\$(git -C "\$path" remote get-url origin 2>/dev/null || echo "")
else
  path=\$PWD
  project=\$(basename "\$path")
  repo=""
fi

# OTEL_RESOURCE_ATTRIBUTES is W3C Baggage format: comma-separated key=value.
# Commas or '=' inside values would break parsing, but neither is expected
# in hostnames, project names, paths under HOME, or git remote URLs.
extra="host.name=\${host},project.name=\${project},project.path=\${path}"
[[ -n \$repo ]] && extra="\${extra},project.repo=\${repo}"

if [[ -n \${OTEL_RESOURCE_ATTRIBUTES:-} ]]; then
  export OTEL_RESOURCE_ATTRIBUTES="\${OTEL_RESOURCE_ATTRIBUTES},\${extra}"
else
  export OTEL_RESOURCE_ATTRIBUTES="\${extra}"
fi

exec "\$REAL_CLAUDE" "\$@"
EOF
chmod +x "$WRAPPER_PATH"

# ---- 4. wire into the active shell's rc ---------------------------------

shell_name=$(basename "${SHELL:-/bin/bash}")
case "$shell_name" in
  zsh)  rc="$HOME/.zshrc"  ;;
  bash) rc="$HOME/.bashrc" ;;
  *)
    echo "WARN: unrecognized shell '$shell_name'." >&2
    echo "      Add this to your rc by hand:" >&2
    echo "        export PATH=\"$INSTALL_DIR:\$PATH\"" >&2
    rc=""
    ;;
esac

if [[ -n $rc ]]; then
  if [[ -f $rc ]] && grep -qF "$MARKER" "$rc"; then
    echo "PATH hook already present in $rc — leaving it alone."
  else
    {
      printf '\n%s\n' "$MARKER"
      # Skip the export if our dir is already in PATH (avoids dupes from
      # other tools that also touch ~/.local/bin).
      printf 'case ":${PATH}:" in *":%s:"*) ;; *) export PATH="%s:$PATH";; esac\n' \
        "$INSTALL_DIR" "$INSTALL_DIR"
    } >>"$rc"
    echo "Added PATH hook to $rc"
  fi
fi

# ---- 5. report -----------------------------------------------------------

echo
echo "Installed:"
echo "  wrapper      $WRAPPER_PATH"
echo "  real binary  $real_claude"
echo
echo "Open a new shell (or run 'exec \$SHELL') and verify:"
echo "  which claude        # should print $WRAPPER_PATH"
echo "  claude --version    # same version as before"
echo
echo "After running claude in a project for ~60s, confirm attributes land:"
echo "  AppMetrics | where TimeGenerated > ago(5m)"
echo "  | where Name == 'claude_code.token.usage'"
echo "  | extend p = parse_json(Properties)"
echo "  | project host = tostring(p['host.name']),"
echo "            project = tostring(p['project.name']),"
echo "            email = tostring(p['user.email']),"
echo "            Sum"
echo "  | take 5"
